---
title: "replication"
author: "Anna Li"
date: "2/26/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(here)
library(knitr)

library(janitor) # Helps clean datasets
library(lubridate) #helps with date cleaning
library(haven)
library(kableExtra)
```



```{r overalldata, echo = FALSE}
#cleaned data is done using script 01datacleaning, with raw data in folder "raw data" under the data folder
main_exp<-read_csv("../inputs/data/main_exp_clean.csv")
followup<-read_csv("../inputs/data/followup_clean.csv")
onlinesurvey<-read_csv("../inputs/data/onlinesurvey_clean.csv")
```

## Figure 2
```{r wedge2, echo = FALSE}
#wedge calculated by guess - actual 
main_exp %>% ggplot(aes(x=(outside_wedge/30)*100),)+
  geom_histogram(aes(y = ..density..),bins=20, fill = "light gray",color = "black",na.rm = TRUE, breaks = seq(-100, 30, by =10)) +
  theme_classic()+
    scale_x_continuous(name= "Wedge (guess% - objective %)",breaks = c(-100,-80,-60,-40,-20,0,20,40,60,80,100),limits =c(-100,100))+
  labs (title = "Wedges in Perception of Others' Beliefs (Working Outside the Home)",subtitle = "(Main Experiment)", caption = "Replication of Wedges in Perception of Others' Beliefs (Working Outside the Home)")+
  scale_y_continuous(name = "Density", breaks = c(0,.005,.01,.015),limits = c(0,.015))+
  geom_vline(xintercept=0, color = "dark red", linetype = "dashed")+
   theme(
        plot.title = element_text(hjust = 0.5),
        plot.subtitle =element_text(hjust = 0.5,face = "italic"),
        plot.caption=element_text(hjust = 0.5)
        )

```


## Table 1

```{r table1data , include = FALSE}
## generate followup info
outside_wife<- followup %>% filter(matched ==1) %>%
  group_by(condition2) %>% 
  summarise(outside = (mean(employed_3mos_out_fl)*100))
outside_wife_all<-followup %>% filter(matched == 1) %>% 
  summarise(outside_all = mean(employed_3mos_out_fl)*100)

##add parentheses around sd observations
add_par <- function(x){
  paste("(",x,")")
}

#All
n<-nrow(main_exp)
m_age<-round(mean(main_exp$age,na.rm= TRUE),2)
sd_age<-add_par(round(sd(main_exp$age,na.rm = TRUE),2))
m_child<-round(mean(main_exp$children,na.rm = TRUE),2)
sd_child<-add_par(round(sd(main_exp$children, na.rm = TRUE),2))
college<-round((sum(main_exp$college_deg)/n)*100,2)
employ<-round((sum(main_exp$employed_now)/n)*100,2)
wife_employ<-round((sum(main_exp$employed_wife)/n)*100,2)
wife_w_outside<-round(outside_wife_all[[1,1]],2)
m_others<-round((sum(main_exp$num_know_per)/n)*100,2)
sd_others<-add_par(round(sd(main_exp$num_know_per,na.rm = TRUE)*100,2))
m_others_friends<-round((sum(main_exp$num_mfs_per)/n)*100,2)
sd_others_friends<-add_par(round(sd(main_exp$num_mfs_per,na.rm = TRUE)*100,2))
all_sum<-c(n, m_age, sd_age, m_child, sd_child, college, employ, wife_employ, wife_w_outside, m_others,sd_others, m_others_friends,sd_others_friends)

#Control
control<-main_exp %>% filter(condition2 == 0)
n<-nrow(control)
m_age<-round(mean(control$age,na.rm= TRUE),2)
sd_age<-add_par(round(sd(control$age,na.rm = TRUE),2))
m_child<-round(mean(control$children,na.rm = TRUE),2)
sd_child<-add_par(round(sd(control$children, na.rm = TRUE),2))
college<-round((sum(control$college_deg)/n)*100,2)
employ<-add_par(round((sum(control$employed_now)/n)*100,2))
wife_employ<-round((sum(control$employed_wife)/n)*100,2)
wife_w_outside<-round(outside_wife[[1,2]],2)
m_others<-round((sum(control$num_know_per)/n)*100,2)
sd_others<-add_par(round(sd(control$num_know_per,na.rm = TRUE)*100,2))
m_others_friends<-round((sum(control$num_mfs_per)/n)*100,2)
sd_others_friends<-add_par(round(sd(control$num_mfs_per,na.rm = TRUE)*100,2))
control_sum<-c(n, m_age, sd_age, m_child, sd_child, college, employ, wife_employ, wife_w_outside, m_others,sd_others, m_others_friends,sd_others_friends)


#Treatment
treatment<-main_exp %>% filter(condition2 == 1)
n<-nrow(treatment)
m_age<-round(mean(treatment$age,na.rm= TRUE),2)
sd_age<-add_par(round(sd(treatment$age,na.rm = TRUE),2))
m_child<-round(mean(treatment$children,na.rm = TRUE),2)
sd_child<-add_par(round(sd(treatment$children, na.rm = TRUE),2))
college<-round((sum(treatment$college_deg)/n)*100,2)
employ<-round((sum(treatment$employed_now)/n)*100,2)
wife_employ<-round((sum(treatment$employed_wife)/n)*100,2)
wife_w_outside<-round(outside_wife[[2,2]],2)
m_others<-round((sum(treatment$num_know_per)/n)*100,2)
sd_others<-add_par(round(sd(treatment$num_know_per,na.rm = TRUE)*100,2))
m_others_friends<-round((sum(treatment$num_mfs_per)/n)*100,2)
sd_others_friends<-add_par(round(sd(treatment$num_mfs_per,na.rm = TRUE)*100,2))
treatment_sum<-c(n, m_age, sd_age, m_child, sd_child, college, employ, wife_employ, wife_w_outside, m_others,sd_others, m_others_friends,sd_others_friends)




```

```{r table1, echo = FALSE}
table1<-cbind(all_sum, control_sum, treatment_sum)
row.names(table1)= c("N","Age","","Number of Children","","College Degree (%)","Employed (%)","Wife Employed (%)", "Wife Working Outside the Home (% retrospective follow-up)", "Other Participants Known (%)", "","Other Participants with Mutual Friends (%)","")
table1 %>% kbl( booktabs = T, col.names=c("All","Control","Treatment"),caption="Summary Statistics (Main Experiment)",
                align=rep('c', 4)) %>% 
                  row_spec(1, hline_after = TRUE) %>%
                  row_spec(9, hline_after = TRUE) %>%
                  row_spec(12, hline_after = TRUE) %>% 
  kable_styling()
```


## Figure 6
```{r fig6data, echo = FALSE}
#adjust to create groups for plotting
value<-na.omit(onlinesurvey$c_outside_guess_frac)
group<-rep("Control",length(value))
c_guess<-cbind(value,group)
c_guess<-data.frame(c_guess)

value<-na.omit(onlinesurvey$t_outside_guess_frac)
group<-rep("Treatment",length(value))
t_guess<-cbind(value,group)
t_guess<-data.frame(t_guess)
df<-rbind(c_guess,t_guess)

#convert to decimal from percentage, for the true proportions
true_cmean<-mean(onlinesurvey$c_outside_mean)/100
true_tmean<-mean(onlinesurvey$t_outside_mean)/100

df<-data.frame(df)
df$group<-as.factor(df$group)
df$value<-as.numeric(df$value)
```


```{r cdf6,echo = FALSE}
#plot cdf graph
df %>% 
  ggplot(aes(x=value))+
 stat_ecdf(aes(color = group,linetype = group),size =0.6)+
  theme_classic()+
  scale_colour_manual(values = c("black","dark red"),labels = c("Control (perceptions about others' answers)","Treatment (Perception about others' beliefs"))+
  scale_y_continuous(name = "Cumulative Probability",breaks = c(0,.2,.4,.6,.8,1), limits = c(0,1))+
  scale_x_continuous(name = "Share of other agreeing",breaks = c(0,.2,.4,.6,.8,1))+
  theme(legend.position = "bottom",legend.title = element_blank(),
        legend.direction = "vertical",
        plot.title = element_text(hjust = 0.5),
        plot.subtitle =element_text(hjust = 0.5,face = "italic"),
        plot.caption=element_text(hjust = 0.5),
        aspect.ratio=0.6
        )+
  scale_linetype_discrete(labels = c("Control (perceptions about others' answers)","Treatment (Perception about others' beliefs"))+
  geom_vline(aes(xintercept = true_cmean))+
  geom_vline(aes(xintercept = true_tmean),col="dark red",linetype ="dashed")+
  annotate(geom = "text",
           label = c("True proportion (treatment)","True proportion(control)"),
           x=c(0.75,1.2),
           y=0,
           vjust = -1,
           hjust = 1,
           size = 2,
           col = c("dark red","black"))+
  labs (title = "Misperceptions about Others' Beliefs",subtitle = "(National Survey)", caption = "Replication Misperceptions about Others' Beliefs")


```



